services:
  - type: web
    name: crickvision
    env: python
    plan: free
    buildCommand: pip install -r reqthing.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    runtime: python-3.10.11
